language: python
sudo: false
python:
  - "3.4"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
  - python3 setup.py install
script: 
  - python3 setup.py test
